server.port=9080
#--------------
# Log information
#--------------
logging.level.root = DEBUG
logging.level.org.springframework.web = DEBUG
logging.level.web = DEBUG
logging.level.org.hibernate = DEBUG
logging.level.org.hibernate.SQL = DEBUG
logging.level.org.hibertnate.type.descriptor.sql.BasicBinder = TRACE

# --------------
# Information about the application
# --------------
spring.main.banner-mode=off
spring.thymeleaf.cache=false

# --------------
# Information about the database
# --------------
spring.datasource.url = jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true
spring.datasource.username = uclmdata
spring.datasource.password = 12345
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto = update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Mensajes SLQ
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.show-sql = true

# --------------
# Information about the server
# --------------
