server.port=9080
#--------------
# Log information
#--------------
# logging.level.root = INFO
# logging.level.org.springframework.web = INFO
# logging.level.web = DEBUG
logging.level.org.hibernate = INFO
logging.level.org.hibernate.SQL = DEBUG
logging.level.org.hibertnate.type.descriptor.sql.BasicBinder = TRACE

# --------------
# Information about the application
# --------------
spring.main.banner-mode=off
spring.thymeleaf.cache=false

# --------------
# Information about the database
# --------------
spring.datasource.url=jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC&allPublicKeyRetrieval=true
spring.datasource.username=uclmdata
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Mensajes SLQ
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# --------------
# Information about the server
# --------------
indice.variable_privada=Enviando mensaje desde application.properties